services:
  - mysql
before_install:
  - mysql -e "create database IF NOT EXISTS moodb;" -uroot
language: node_js
node_js:
  - "node"
before_script:
  - webpack
  - npm start
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_deploy:
- echo "Deploy Finished!"
