sudo:
  - false
language: node_js
node_js:
  - '5.8'
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS moodb;" -u root #install database for user 'travis'
before_script:
  - npm install -g webpack
  - npm install -g mocha
  - npm install -g chai
  - babel-node server/index.js
  - npm test #run tests in specs/server/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 #delay start of xvfb
after_script:
- echo "Build Finished!"

#./specs/server/databaseTest.js
#./specs/server/moodModelTest.js
#./specs/server/quoteModelTest.js
#./specs/server/userControllerTest.js
#./specs/server/userModelTest.js
#